annotations:
  # Core bundle annotations.
  operators.operatorframework.io.bundle.mediatype.v1: registry+v1
  operators.operatorframework.io.bundle.manifests.v1: manifests/
  operators.operatorframework.io.bundle.metadata.v1: metadata/
  operators.operatorframework.io.bundle.package.v1: kubernetes-nmstate-operator
  operators.operatorframework.io.bundle.channels.v1: 4.12,alpha
  operators.operatorframework.io.bundle.channel.default.v1: 4.12
  operators.operatorframework.io.metrics.builder: operator-sdk-v1.22.2
  operators.operatorframework.io.metrics.mediatype.v1: metrics+v1
  operators.operatorframework.io.metrics.project_layout: go.kubebuilder.io/v3
