required = ["k8s.io/code-generator/cmd/client-gen"]

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-8.0"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.11"

[[constraint]]
  version = "0.1.2"
  name = "kubevirt.io/qe-tools"

# https://github.com/golang/dep/issues/1799
[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"
