apiVersion: v1
kind: Namespace
metadata:
  name: {{ .HandlerNamespace }}
{{- if .IsOpenShift }}
  annotations:
    openshift.io/node-selector: ""
{{- end }}
  labels:
    name: {{ .HandlerNamespace }}
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
{{- if .IsOpenShift }}
    openshift.io/cluster-monitoring: "true"
{{- end }}
