{{define "handlerPrefix"}}{{with $prefix := .HandlerPrefix}}{{$prefix | printf "%s-"}}{{end -}}{{end}}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: '{{template "handlerPrefix" .}}nmstate-handler'
  namespace: '{{ .HandlerNamespace }}'
  labels:
    nmstate.io: ""
