---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nmstate-handler
  namespace: nmstate
spec:
  selector:
    matchLabels:
      name: nmstate-handler
  template:
    metadata:
      labels:
        app: kubernetes-nmstate
        name: nmstate-handler
    spec:
      # Needed to force vlan filtering config with iproute commands until
      # future nmstate/NM is in place.
      # https://github.com/nmstate/nmstate/pull/440
      hostNetwork: true
      serviceAccountName: nmstate-handler
      nodeSelector:
        beta.kubernetes.io/arch: amd64
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: nmstate-handler
          args:
          - --v=production
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          command:
          - kubernetes-nmstate
          env:
            - name: WATCH_NAMESPACE
              value: ""
            # FIXME: Communication to etcd not working at openshift, looks like
            # related to caBundle
            #- name: RUN_WEBHOOK_SERVER
            #  value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nmstate-handler"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_NETWORK_STATE_REFRESH_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: nmstate-config
                  key: node_network_state_refresh_interval
            - name: INTERFACES_FILTER
              valueFrom:
                configMapKeyRef:
                  name: nmstate-config
                  key: interfaces_filter
            - name: WEBHOOK_PORT
              value: "54874"
            - name: ENABLE_PROFILER
              value: "False"
            - name: PROFILER_PORT
              value: "6060"
          volumeMounts:
          - name: dbus-socket
            mountPath: /run/dbus/system_bus_socket
          securityContext:
            privileged: true
      volumes:
      - name: dbus-socket
        hostPath:
          path: /run/dbus/system_bus_socket
          type: Socket
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nmstate-handler-worker
  namespace: nmstate
spec:
  selector:
    matchLabels:
      name: nmstate-handler-worker
  template:
    metadata:
      labels:
        app: kubernetes-nmstate
        name: nmstate-handler-worker
    spec:
      # Needed to force vlan filtering config with iproute commands until
      # future nmstate/NM is in place.
      # https://github.com/nmstate/nmstate/pull/440
      hostNetwork: true
      serviceAccountName: nmstate-handler
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: NotIn
                    values:
                      - ""
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
        - name: nmstate-handler
          args:
            - --v=production
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          command:
            - kubernetes-nmstate
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nmstate-handler"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_NETWORK_STATE_REFRESH_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: nmstate-config
                  key: node_network_state_refresh_interval
            - name: INTERFACES_FILTER
              valueFrom:
                configMapKeyRef:
                  name: nmstate-config
                  key: interfaces_filter
          volumeMounts:
            - name: dbus-socket
              mountPath: /run/dbus/system_bus_socket
          securityContext:
            privileged: true
      volumes:
        - name: dbus-socket
          hostPath:
            path: /run/dbus/system_bus_socket
            type: Socket
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nmstate-config
  namespace: nmstate
data:
  node_network_state_refresh_interval: "5"
  interfaces_filter: "veth*"
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: nmstate-webhook
#  namespace: nmstate
#  labels:
#    app: kubernetes-nmstate
#spec:
#  publishNotReadyAddresses: true
#  ports:
#    - port: 443
#      targetPort: 54874
#  selector:
#    name: nmstate-handler
#---
#apiVersion: admissionregistration.k8s.io/v1beta1
#kind: MutatingWebhookConfiguration
#metadata:
#  name: nmstate
#  labels:
#    app: kubernetes-nmstate
#webhooks:
#  - name: nodenetworkconfigurationpolicies-mutate.nmstate.io
#    clientConfig:
#      service:
#        name: nmstate-webhook
#        namespace: nmstate
#        path: "/nodenetworkconfigurationpolicies-mutate"
#    rules:
#      - operations: ["CREATE", "UPDATE"]
#        apiGroups: ["*"]
#        apiVersions: ["v1alpha1"]
#        resources: ["nodenetworkconfigurationpolicies"]
#  - name: nodenetworkconfigurationpolicies-status-mutate.nmstate.io
#    clientConfig:
#      service:
#        name: nmstate-webhook
#        namespace: nmstate
#        path: "/nodenetworkconfigurationpolicies-status-mutate"
#    rules:
#      - operations: ["CREATE", "UPDATE"]
#        apiGroups: ["*"]
#        apiVersions: ["v1alpha1"]
#        resources: ["nodenetworkconfigurationpolicies/status"]
#  - name: nodenetworkconfigurationpolicies-timestamp-mutate.nmstate.io
#    clientConfig:
#      service:
#        name: nmstate-webhook
#        namespace: nmstate
#        path: "/nodenetworkconfigurationpolicies-timestamp-mutate"
#    rules:
#      - operations: ["CREATE", "UPDATE"]
#        apiGroups: ["*"]
#        apiVersions: ["v1alpha1"]
#        resources: ["nodenetworkconfigurationpolicies", "nodenetworkconfigurationpolicies/status"]
