---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nmstate-handler
  namespace: nmstate
spec:
  selector:
    matchLabels:
      name: nmstate-handler
  template:
    metadata:
      labels:
        app: kubernetes-nmstate
        name: nmstate-handler
    spec:
      # Needed to force vlan filtering config with iproute commands until
      # future nmstate/NM is in place.
      # https://github.com/nmstate/nmstate/pull/440
      hostNetwork: true
      serviceAccountName: nmstate-handler
      nodeSelector:
        beta.kubernetes.io/arch: amd64
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: nmstate-handler
          args:
          - --v=production
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          command:
          - kubernetes-nmstate
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: RUN_WEBHOOK_SERVER
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nmstate-handler"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: WEBHOOK_PORT
              value: "54874"
            - name: ENABLE_PROFILER
              value: "False"
            - name: PROFILER_PORT
              value: "6060"
            - name: CONFIG_PATH
              value: "/etc/config/nmstate.yaml"
          volumeMounts:
          - name: dbus-socket
            mountPath: /run/dbus/system_bus_socket
          - name: config-volume
            mountPath: /etc/config
          securityContext:
            privileged: true
      volumes:
      - name: dbus-socket
        hostPath:
          path: /run/dbus/system_bus_socket
          type: Socket
      - name: config-volume
        configMap:
          # Provide the name of the ConfigMap containing the file
          # configmap can be created from file or with this data :
          # Example:
          # data:
          #   nmstate.yaml: |
          #     interfaces_filter: "veth*"
          # it's full path must
          # be set in CONFIG_PATH param
          # to add to the container
          name: nmstate-config
          optional: true
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nmstate-handler-worker
  namespace: nmstate
spec:
  selector:
    matchLabels:
      name: nmstate-handler-worker
  template:
    metadata:
      labels:
        app: kubernetes-nmstate
        name: nmstate-handler-worker
    spec:
      # Needed to force vlan filtering config with iproute commands until
      # future nmstate/NM is in place.
      # https://github.com/nmstate/nmstate/pull/440
      hostNetwork: true
      serviceAccountName: nmstate-handler
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: NotIn
                    values:
                      - ""
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
        - name: nmstate-handler
          args:
            - --v=production
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          command:
            - kubernetes-nmstate
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nmstate-handler"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ENABLE_PROFILER
              value: "False"
            - name: PROFILER_PORT
              value: "6060"
            - name: CONFIG_PATH
              value: "/etc/config/nmstate.yaml"
          volumeMounts:
            - name: dbus-socket
              mountPath: /run/dbus/system_bus_socket
            - name: config-volume
              mountPath: /etc/config
          securityContext:
            privileged: true
      volumes:
        - name: dbus-socket
          hostPath:
            path: /run/dbus/system_bus_socket
            type: Socket
        - name: config-volume
          configMap:
            # Provide the name of the ConfigMap containing the file
            # configmap can be created from file or with this data :
            # Example:
            # data:
            #   nmstate.yaml: |
            #     interfaces_filter: "veth*"
            # it's full path must
            # be set in CONFIG_PATH param
            # to add to the container
            name: nmstate-config
            optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: nmstate-webhook
  namespace: nmstate
  labels:
    app: kubernetes-nmstate
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 443
      targetPort: 54874
  selector:
    name: nmstate-handler
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: nmstate
  labels:
    app: kubernetes-nmstate
webhooks:
  - name: nodenetworkconfigurationpolicies-mutate.nmstate.io
    clientConfig:
      service:
        name: nmstate-webhook
        namespace: nmstate
        path: "/nodenetworkconfigurationpolicies-mutate"
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["v1alpha1"]
        resources: ["nodenetworkconfigurationpolicies"]
  - name: nodenetworkconfigurationpolicies-status-mutate.nmstate.io
    clientConfig:
      service:
        name: nmstate-webhook
        namespace: nmstate
        path: "/nodenetworkconfigurationpolicies-status-mutate"
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["v1alpha1"]
        resources: ["nodenetworkconfigurationpolicies/status"]
  - name: nodenetworkconfigurationpolicies-timestamp-mutate.nmstate.io
    clientConfig:
      service:
        name: nmstate-webhook
        namespace: nmstate
        path: "/nodenetworkconfigurationpolicies-timestamp-mutate"
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["v1alpha1"]
        resources: ["nodenetworkconfigurationpolicies", "nodenetworkconfigurationpolicies/status"]
