kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-nmstate
subjects:
- kind: ServiceAccount
  name: kubernetes-nmstate
roleRef:
  kind: Role
  name: kubernetes-nmstate
  apiGroup: rbac.authorization.k8s.io
