---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: nmstate
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostNetwork: true
allowHostIPC: false
allowHostPID: false
allowHostPorts: false
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:nmstate:nmstate-handler
