name: Latest-Job slack bot

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./automation/nmstate-latest-reporter

jobs:
  build-and-run-slack-bot:
    name: Latest-job slack bot
    if: github.repository == 'nmstate/kubernetes-nmstate'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./automation/nmstate-latest-reporter/go.mod

      - name: Build
        run: go build -v .

      - name: run
        env:
          NMSTATE_SLACK_WEBHOOK_URL: ${{ secrets.NMSTATE_SLACK_WEBHOOK_URL }}
        run: |
          ./nmstate-latest-reporter --notify-on=failure --notify-on=stale
